version: '3.3'

services:
  web:
    container_name: web-gestao-ativos
    build: .
    command: npm run dev
    restart: always
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/gestao-ativos

  mongo:
    container_name: db-gestao-ativos
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db


